# Generated by Django 4.0.6 on 2022-08-04 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_followers', models.IntegerField(default=0, null=True)),
                ('total_followings', models.IntegerField(default=0, null=True)),
                ('dp', models.ImageField(upload_to='dp/')),
                ('followers', models.ManyToManyField(null=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(null=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(upload_to='media/')),
                ('caption', models.TextField(null=True)),
                ('comments', models.TextField(default='', null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('liked_by', models.ManyToManyField(null=True, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
                ('post_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('msguser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msguser', to=settings.AUTH_USER_MODEL)),
                ('reciepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
