# Generated by Django 4.0.6 on 2022-08-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_comments_comment_by_comments_comment_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
