# Generated by Django 4.0.6 on 2022-08-04 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_message_msguser_alter_message_reciepient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msguser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msguser', to=settings.AUTH_USER_MODEL),
        ),
    ]
